apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/${ENVIRONMENT}/${CLUSTER}
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-config
  validation: client